#!/usr/bin/env sh
# ================================================================================
# Variables
# ================================================================================
dotmac="$HOME/.mac"
bash="$HOME/.oh-my-bash"
repos="https://github.com/jimzhan/dotmac.git"

# ================================================================================
# Functions
# ================================================================================
log() {
    printf '\033[0;34m%s\033[0m\n' "${1}"
}

info() {
    printf "\e[34m[I]\e[0m ${1}\n"
}

error() {
    printf "\e[31m[✘]\e[0m ${1}\n"
}

success() {
    printf "\e[32m[✔]\e[0m ${1}\n"
}

# to error out
warn() {
  echo "$1" >&2
}

die() {
  warn "$1"
  exit 1
}

# forcely remove any existing link or directory.
deldir() {
  if [ -L $1 ]; then
    unlink "$1"
  elif [ -d $1 ]; then
    rm -rf "$1"
  fi
}

# forcely remove any existing link or file before creating custom links.
link() {
  if [ -h $2 ] ; then
    unlink $2
  elif [ -e $2 ]; then
    rm $2
  fi
  ln -s $1 $2
}

# ---------------------------------------------------------------------------
# Setup Foundations
# ---------------------------------------------------------------------------
brew install direnv terminal-notifier

if [ ! -d $dotmac ]; then
  log "Setting up my Mac..."
  if [ ! -d $bash ]; then
    git clone git://github.com/ohmybash/oh-my-bash.git $bash
  fi

  # Bash (as dotfiles's submodule)
  log "Setting up Bash..."
  export BASH="$bash"
  chsh -s /bin/bash
  success "Bash installed."

  if [ ! -d "$HOME/.ssh" ]; then
    mkdir $HOME/.ssh
  fi
else
  log "Updating my Mac..."
  cd $dotmac
  git pull

  # bash
  log "Updating Bash..."
  cd $bash
  git pull
fi


# ---------------------------------------------------------------------------
# LaunchAgent Services
# ---------------------------------------------------------------------------
if [ ! -d "$HOME/Library/LaunchAgents" ]; then
  mkdir $HOME/Library/LaunchAgents
fi

for filepath in $dotmac/LaunchAgents/*.plist
do
  filename=$(basename $filepath)
  link $dotmac/LaunchAgents/$filename   $HOME/Library/LaunchAgents/$filename
  launchctl load $HOME/Library/LaunchAgents/$filename
done


# ---------------------------------------------------------------------------
# Ensure We Have Linked All dot files.
# ---------------------------------------------------------------------------
link    $dotmac/bash/profile                        $HOME/.profile
link    $dotmac/bash/bash_profile                   $HOME/.bash_profile
link    $dotmac/bash/bashrc                         $HOME/.bashrc
link    $dotmac/ssh/config                          $HOME/.ssh/config
link    $dotmac/git/gitconfig                       $HOME/.gitconfig
link    $dotmac/iTerm/com.googlecode.iterm2.plist   $HOME/Library/Preferences/com.googlecode.iterm2.plist
cp      $dotmac/fonts/*                             $HOME/Library/Fonts/
