#!/usr/bin/env sh
# ================================================================================
# Variables
# ================================================================================
MAC="$HOME/.mac"
OMB="$HOME/.oh-my-bash"

# ================================================================================
# Functions
# ================================================================================
log() {
    printf '\033[0;34m%s\033[0m\n' "${1}"
}

info() {
    printf "\e[34m[I]\e[0m ${1}\n"
}

error() {
    printf "\e[31m[✘]\e[0m ${1}\n"
}

success() {
    printf "\e[32m[✔]\e[0m ${1}\n"
}

# to error out
warn() {
  echo "$1" >&2
}

die() {
  warn "$1"
  exit 1
}

# forcely remove any existing link or directory.
deldir() {
  if [ -L $1 ]; then
    unlink "$1"
  elif [ -d $1 ]; then
    rm -rf "$1"
  fi
}

# forcely remove any existing link or file before creating custom links.
link() {
  if [ -h $2 ] ; then
    unlink $2
  elif [ -e $2 ]; then
    rm $2
  fi
  ln -s $1 $2
}

# ---------------------------------------------------------------------------
# Setup Foundations
# ---------------------------------------------------------------------------
if [ ! -d $MAC ]; then
  log "Setting up my Mac..."
  if [ ! -d $OMB ]; then
    git clone https://github.com/ohmybash/oh-my-bash $OMB
  fi

  # Bash (as dotfiles's submodule)
  log "Setting up Bash..."
  export BASH="$OMB"
  chsh -s /bin/bash
  success "Bash installed."

  if [ ! -d "$HOME/.ssh" ]; then
    mkdir $HOME/.ssh
  fi
else
  log "Updating my Mac..."
  cd $MAC
  git pull

  # bash
  log "Updating Bash..."
  cd $OMB
  git pull
fi


# ---------------------------------------------------------------------------
# LaunchAgent Services
# ---------------------------------------------------------------------------
if [ ! -d "$HOME/Library/LaunchAgents" ]; then
  mkdir $HOME/Library/LaunchAgents
fi

for filepath in $MAC/LaunchAgents/*.plist
do
  filename=$(basename $filepath)
  link $MAC/LaunchAgents/$filename   $HOME/Library/LaunchAgents/$filename
  launchctl load $HOME/Library/LaunchAgents/$filename
done

if [ ! -d "$HOME/.ssh" ]; then
  mkdir $HOME/.ssh
fi
if [ ! -d "$OMB/themes/funbox" ]; then
  mkdir $OMB/themes/funbox
fi
# ---------------------------------------------------------------------------
# Ensure We Have Linked All dot files.
# ---------------------------------------------------------------------------
link    $MAC/bash/profile                        $HOME/.profile
link    $MAC/bash/bash_profile                   $HOME/.bash_profile
link    $MAC/bash/bashrc                         $HOME/.bashrc
link    $MAC/ssh/config                          $HOME/.ssh/config
link    $MAC/git/gitconfig                       $HOME/.gitconfig
link    $MAC/iTerm/com.googlecode.iterm2.plist   $HOME/Library/Preferences/com.googlecode.iterm2.plist
link    $MAC/bash/funbox.theme.sh                $OMB/themes/funbox/funbox.theme.sh 
cp      $MAC/fonts/*                             $HOME/Library/Fonts/
