#!/usr/bin/env sh
# ================================================================================
# Variables
# ================================================================================
dotmac="$HOME/.mac"
repos="https://github.com/jimzhan/dotmac.git"
zsh="$HOME/.oh-my-zsh"


# ================================================================================
# Functions
# ================================================================================
log() {
    printf '\033[0;34m%s\033[0m\n' "${1}"
}

info() {
    printf "\e[34m[I]\e[0m ${1}\n"
}

error() {
    printf "\e[31m[✘]\e[0m ${1}\n"
}

success() {
    printf "\e[32m[✔]\e[0m ${1}\n"
}

# to error out
warn() {
  echo "$1" >&2
}

die() {
  warn "$1"
  exit 1
}

# forcely remove any existing link or directory.
deldir() {
  if [ -L $1 ]; then
    unlink "$1"
  elif [ -d $1 ]; then
    rm -rf "$1"
  fi
}

# forcely remove any existing link or file before creating custom links.
link() {
  if [ -h $2 ] ; then
    unlink $2
  elif [ -e $2 ]; then
    rm $2
  fi
  ln -s $1 $2
}

# ---------------------------------------------------------------------------
# Setup Foundations
# ---------------------------------------------------------------------------
brew install terminal-notifier
if [ ! -d $dotmac ]; then
  log "Setting up my Mac..."
  if [ ! -d $zsh ]; then
    git clone git://github.com/robbyrussell/oh-my-zsh.git $zsh
  fi
  git clone --recursive $repos $dotmac

  # zsh (as dotfiles's submodule)
  log "Setting up ZSH..."
  export ZSH="$zsh"
  chsh -s /bin/zsh
  success "ZSH installed."

  if [ ! -d "$HOME/.ssh" ]; then
    mkdir $HOME/.ssh
  fi
else
  log "Updating dotfiles..."
  cd $dotmac
  git pull
  git submodule update --init --recursive

  # zsh
  log "Updating ZSH..."
  cd $zsh
  git pull
fi


# ---------------------------------------------------------------------------
# LaunchAgent Services
# ---------------------------------------------------------------------------
if [ ! -d "$HOME/Library/LaunchAgents" ]; then
  mkdir $HOME/Library/LaunchAgents
fi

for filepath in $dotmac/LaunchAgents/*.plist
do
  filename=$(basename $filepath)
  link $dotmac/LaunchAgents/$filename   $HOME/Library/LaunchAgents/$filename
  launchctl load $HOME/Library/LaunchAgents/$filename
done


# ---------------------------------------------------------------------------
# Ensure We Have Linked All dot files.
# ---------------------------------------------------------------------------
link $dotmac/zsh/zshrc            $HOME/.zshrc
link $dotmac/ssh/config           $HOME/.ssh/config
cp ${dotfiles}/fonts/*            $HOME/Library/Fonts/
